import ContactCard from "@/components/Contact/contact-card";
import ProfileImage from "@/components/About/profile-img";
import FacebookIcon from "@mui/icons-material/Facebook";
import InstagramIcon from "@mui/icons-material/Instagram";
import Head from "next/head";
import Link from "next/link";

function ContactPage() {
    return (
        <>
            <Head>
                <title>Ksahlos - Contact</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className="md:flex justify-center items-center bg-[#F2F2F2] w-full h-screen">
                <div className="flex justify-center items-center w-full h-screen ">
                    <div
                        className='mb-20 2xl:mb-96'
                        data-aos="zoom-in-up"
                        data-aos-duration="800"
                    >
                        <ProfileImage width={550} height={550}/>
                    </div>
                </div>
                <div
                    className="w-full p-4 mb-20 2xl:mb-96 mr-11 2xl:mr-96"
                    data-aos="zoom-in-up"
                    data-aos-delay="200"
                    data-aos-duration="800"
                >
                    <div className='mb-10 p-2'>
                        <h1 className="text-4xl my-4">Contact</h1>
                        <hr className="mb-4 "/>
                        <p className="my-6">
                            Now, as you were able to get a picture of who I am, how I work and what I can do, it is up
                            to
                            you to contact me and lay the foundation for a new and successful relationship.
                        </p>
                        <div>
                            <ContactCard/>
                        </div>
                    </div>
                    <div className='mt-10 p-2'>
                        <h1 className='text-3xl my-4'>Or Find Me on Social Media</h1>
                        <hr className="mb-4 "/>
                        <div className='my-3'>
                            <Link href='https://www.facebook.com/konstantinos.sahlos'>
                                <FacebookIcon/>
                                <span className='mx-2'>Konstantinos Sahlos</span>
                            </Link>
                        </div>
                        <div className='my-3'>
                            <Link href='https://www.instagram.com/ksahlos_photo/'>
                                <InstagramIcon/>
                                <span className='mx-2'>Ksahlos Photo</span>
                            </Link>
                        </div>
                    </div>
                </div>
            </div>
        </>
    );
}

export default ContactPage;
