'use client'
import { useAuth } from "@/utilities/auth-utility";
import { useRouter } from "next/navigation";
import { useState } from "react";
import NewPhotoBlock from "@/components/Admin/New-Photo-Block/new-photo-block";
import EditPhotosBlock from "@/components/Admin/Edit-Photos-Block/edit-photo-block";
import ListBar from "@/components/Admin/List-Bar/list-bar";
import Link from "next/link";
import Head from "next/head";

function AdminPanelPage() {
    const [isNewPhotoBlockVisible, setIsNewPhotoBlockVisible] = useState(false);
    const [isEditPhotosBlockVisible, setIsEditPhotosBlockVisible] = useState(false);

    const user = useAuth();
    const router = useRouter();

    function newPhotoBlockHandler() {
        setIsNewPhotoBlockVisible(true);
        setIsEditPhotosBlockVisible(false);
    }

    function editPhotoBlockHandler() {
        setIsNewPhotoBlockVisible(false);
        setIsEditPhotosBlockVisible(true);
    }

    console.log(user);
    return (
        <>
            <Head>
                <title>Ksahlos - Admin Panel</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <meta name="robots" content="noindex" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="flex h-full">
                {!user && (
                    <div className="flex flex-col w-full justify-center items-center">
                        <h1>
                            <span className="font-bold">Warning!</span> You do not have the privileges to enter this page.
                        </h1>
                        <h1>
                            Please{" "}
                            <Link href="/login" className="underline text-cyan-700 hover:text-cyan-900">
                                Login
                            </Link>
                        </h1>
                    </div>
                )}
                {user && (
                    <>
                        <ListBar onNewPhotoBlockHandler={newPhotoBlockHandler} onEditPhotoBlockHandler={editPhotoBlockHandler} />
                        <div className="flex flex-1 justify-center items-center border-2 border-gray-200 rounded mx-3 shadow-md p-8">
                            {isNewPhotoBlockVisible && <NewPhotoBlock />}
                            {isEditPhotosBlockVisible && <EditPhotosBlock />}
                        </div>
                    </>
                )}
            </div>
        </>
    );
}

export default AdminPanelPage;
