'use client'
import MasonryGrid from "@/components/Masonry-Grid/masonry-grid";
import Head from "next/head";
import {useEffect, useState} from "react";
import {getPhotos} from "@/firebase/get-photos";
import Spinner from "@/components/Spinner/spinner";

function MinimalisticGallery() {
    const [photosData, setPhotosData] = useState([])
    const category = 'conceptual'

    useEffect(() => {
        fetchData()
    }, []);

    async function fetchData() {
        try {
            const data = await getPhotos(category);
            setPhotosData(data);
        } catch (error) {
            console.error("Error fetching data:", error);
        }
    }

    return (
        <>
            <div>
                <Head>
                    <title>Ksahlos - Local Art</title>
                    <meta name="description" content="Generated by create next app"/>
                    <meta name="viewport" content="width=device-width, initial-scale=1"/>
                    <link rel="icon" href="/favicon.ico"/>
                </Head>
                <div className="p-2">
                    {photosData.length > 0
                        ? <MasonryGrid photos={photosData}/>
                        : <div className='flex justify-center items-center w-full h-screen'>
                            <Spinner/>
                        </div>
                    }
                </div>
            </div>
        </>
    );
}

export default MinimalisticGallery;
