'use client'
import Head from "next/head";
import Image from "next/image";
import {TypeAnimation} from "react-type-animation";

export default function Home() {
    const homepagePhoto = 'https://firebasestorage.googleapis.com/v0/b/photography-site-ksahlos-84194.appspot.com/o/Others%2Fswan.jpeg?alt=media&token=6c1692b6-a13a-4719-af0d-aa821e958402'

    return (
        <>
            <Head>
                <title>Ksahlos - Homepage</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            {homepagePhoto.length > 0 && (
                <div className="relative z-[-1] w-full h-full">
                    <Image src={homepagePhoto} alt="background image" layout="fill" objectFit="cover" loading="eager"
                           quality={70}/>
                    <div className="absolute inset-0 flex items-center justify-center">
                        <div>
                            <h1 className="text-[25px] text-white font-thin" data-aos="zoom-in-up">
                                Fine - Art Photography
                            </h1>
                            <p className="text-center italic font-thin text-white text-[12px]" data-aos="zoom-in-up"
                               data-aos-delay="100">
                                <TypeAnimation sequence={["A stylish world through my lens"]} speed={30}
                                               cursor={false}/>
                            </p>
                        </div>
                    </div>
                </div>
            )}
        </>
    )
}
