'use client'
import LoginForm from "@/components/Login-Form/login-form";
import { useAuth } from "@/utilities/auth-utility";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import Head from "next/head";

function LoginPage() {
    const [isUserLoggedIn, setIsUserLoggedIn] = useState(false);
    const [checkingUserState, setCheckingUserState] = useState(true);
    const user = useAuth();
    const router = useRouter();

    useEffect(() => {
        if (user) {
            setIsUserLoggedIn(true);
            router.push("/admin"); //TODO:CHANGE
        } else {
            setIsUserLoggedIn(false);
            setCheckingUserState(false);
        }
    }, []);
    console.log(user);
    return (
        <>
            <Head>
                <title>Ksahlos - Login</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <meta name="robots" content="noindex"/>
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="bg-[#F2F2F2] w-full h-full flex justify-center items-center">
                {checkingUserState && <div>CHECKING USER PRIVILEGES</div>}
                {!checkingUserState && !isUserLoggedIn && <LoginForm />}
            </div>
        </>
    );
}

export default LoginPage;
