import Head from "next/head";
import PricingBoxes from "@/components/Pricing/pricing-boxes";

function PricingPage() {
    return (
        <>
            <Head>
                <title>Ksahlos - Pricing</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className="w-full h-full bg-[#F2F2F2] flex-col flex justify-around items-center">
                <PricingBoxes/>
                <p className='text-xs'>Above prices, do not include VAT 24%</p>
            </div>

        </>
    );
}

export default PricingPage;
